# Generated by Django 4.2.19 on 2025-05-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('query', models.CharField(max_length=500)),
                ('results', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
